/icp_registration:
  ros__parameters:
    use_sim_time: false
    rough_leaf_size: 0.4
    refine_leaf_size: 0.1
    pcd_path: "/home/spr-rc/Sentry_ws/src/SPR-RM-Sentry/src/rm_localization/fast_lio/PCD/RMUC.pcd"
    map_frame_id: "map"
    odom_frame_id: "odom"
    laser_frame_id: "livox_frame"
    pointcloud_topic: "/livox/lidar/pointcloud"
    thresh: 0.1
    xy_offset: 0.2
    yaw_offset: 30.0
    yaw_resolution: 10.0
    initial_pose: [15.37, -4.79, 0.0, 0.0, 0.0, 179] # x,y,z,roll,pitch,yaw
